version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: ./vendor/bin/phpunit -v
      - run: ./vendor/bin/phpcs
      - store_test_results:
          path: tests/_output
      - store_artifacts:
          path: tests/_output