version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run: mkdir -p tests/_results
      - run: mkdir tests/_artifacts
      - run: ./vendor/bin/phpunit -v --log-junit tests/_results/phpunit.xml
      - run: ./vendor/bin/phpcs --report=tests/_artifacts/phpcs.txt
      - store_test_results:
          path: tests/_results
      - store_artifacts:
          path: tests/_artifacts